### ISSUE TITLE
You have exposed client id / secrets and gmail credentials on your project

### ISSUE THREAD

**Issue by pgerlich** [selin1998/news-feed-project#8]
```
server:
  port: ${PORT:9090}


spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/feed
    username: postgres
    password: password

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 275467666884234
            client-secret: 18c6977e20cb1374b2085df443aa684d
            scope:
              - email
              - public_profile
          google:
            clientId: 747054116050-j25974gvn8i27h044kdddi3714rr8s74.apps.googleusercontent.com
            clientSecret: EitCAZgKbH-Ae0ymTBLJJoVG


# ===============================
# = JPA configurations
# ===============================
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true

# ===============================
# = MAIL configurations
# ===============================
  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      username: new.news.feed.2020@gmail.com
      password: guxzgbeckqxrlisn
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false
```
We discovered this while running tests with our product @ https://blubracket.com/
